### ISSUE TITLE
Allow passing in data from action config to EJS

### ISSUE THREAD

**Issue by jonchurch** [pkgjs/meet#206]
We have a template which is exactly the same between two different types of meetings, except for the meeting link.

I want to be able to add in a string to be available to my EJS template at render time.

https://github.com/expressjs/discussions/pull/283

For example, I want to be able to do something like:

```yaml
     uses: 'pkgjs/meet@v0'
        with:
          issueTitle: '<%= date.toFormat("yyyy-MM-dd") %> Express TC Meeting'
          // ...
          data:
			meetingLink: "https://example.com"
```
